### ISSUE TITLE
Odd table header style on mobile

### ISSUE THREAD

**Issue by MattMcAdams** [UAB-IT/linear#116]
**Describe the bug**
On smaller screens, the table header is squished into one table cell instead of behaving as expected.

**URL**
https://www.uab.edu/it/home/policies/data-classification/classification-overview

**To Reproduce**
1. Go to 'https://www.uab.edu/it/home/policies/data-classification/classification-overview'
2. Resize browser to smaller width
3. Scroll down to "Can you store or share data?" table
4. See visual error

**Expected behavior**
The table header should span the width of the entire table, with a header for each column.

**Screenshots**
<img width="725" alt="Screen Shot 2020-08-24 at 10 06 49 AM" src="https://user-images.githubusercontent.com/26938709/91062094-e92ad980-e5f1-11ea-8079-f3e3219e870a.png">

**Device Information**
You can get this data from https://supportally.com/
 - Operating System: OSX 11 Beta 5
 - Browser & Version: Firefox 80.0
 - Browser Size: 810 x 943
 - Screen Size: 1680 x 1050
 - JavaScript enabled? Yes

**Additional Context**
While inspecting the element with dev tools, the issue seems to be the following piece of CSS from linear.css

```css
@media only screen and (max-width: 1024px) and (min-width: 300px) {
    body.linear #content th,
    body.linear #content thead {
        display: table-cell;
    }
}
```
